require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "scapeshift"
    gem.summary = %Q{Magic: The Gathering Oracle web scraper}
    gem.description = %Q{Powers the Scapeshift web API.}
    gem.email = "joshua.s.lindsey@gmail.com"
    gem.homepage = "http://github.com/jlindsey/scapeshift"
    gem.authors = ["Josh Lindsey"]
    gem.add_development_dependency "bundler"
    gem.add_dependency "nokogiri"
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |test|
    test.libs << 'test'
    test.pattern = 'test/**/test_*.rb'
    test.verbose = true
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install spicycode-rcov"
  end
end

task :test

task :default => :test

require 'yard'
YARD::Rake::YardocTask.new

desc "Remove docs generated by yard"
task :clobber_yard do
  puts "rm -rf doc/"
  %x{rm -rf doc/}
end

desc "Searches for all @todo tags and prints them"
task :todos do
  puts %x{grep -inr "@todo" lib/}
end
