# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scapeshift}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Lindsey"]
  s.date = %q{2010-04-05}
  s.description = %q{}
  s.email = %q{joshua.s.lindsey@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardopts",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/scapeshift.rb",
     "lib/scapeshift/card.rb",
     "lib/scapeshift/crawler.rb",
     "lib/scapeshift/crawlers.rb",
     "lib/scapeshift/crawlers/cards.rb",
     "lib/scapeshift/crawlers/meta.rb",
     "lib/scapeshift/crawlers/single.rb",
     "lib/scapeshift/errors.rb",
     "scapeshift.gemspec",
     "test/helper.rb",
     "test/test_card.rb",
     "test/test_card_crawler.rb",
     "test/test_crawler_main.rb",
     "test/test_meta_crawler.rb",
     "test/test_single_crawler.rb"
  ]
  s.homepage = %q{http://github.com/jlindsey/scapeshift}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Magic: The Gathering Oracle web scraper}
  s.test_files = [
    "test/helper.rb",
     "test/test_crawler_main.rb",
     "test/test_meta_crawler.rb",
     "test/test_card_crawler.rb",
     "test/test_single_crawler.rb",
     "test/test_card.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

